---
apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - image: kodekloud/event-simulator
    name: webapp
    volumeMounts:
    - mountPath: /log
      name: webapp-volume
  volumes:
  - name: webapp-volume
    hostPath:
      path: /var/log/webapp
      type: Directory